services:
  - type: web
    name: portfolio
    env: node
    plan: free
    buildCommand: npm install && node render-deploy.js
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true