services:
  - type: web
    name: portfolio
    env: node
    plan: free
    buildCommand: npm install && npm install -g vite esbuild @vitejs/plugin-react tailwindcss && vite build && node build.js
    startCommand: node start.js